# Generated by Django 3.0.6 on 2020-06-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
